// IF YOU HAVE NOT ALREADY READ PATIENT_CARE_RULES.md, STOP AND READ IT BEFORE EDITING THIS FILE.
(function(){
'use strict';
const KEY='pc_home_bp_v1';
const LANG_KEY='pc_patient_language';
const DAYS=7;
const SESSIONS=['am','pm'];
function lang(){return localStorage.getItem(LANG_KEY)==='ar'?'ar':'en'}
function ar(){return lang()==='ar'}
function t(en,arText){return ar()?arText:en}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{start:'',rows:{}}}catch(e){return {start:'',rows:{}}}}
function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
function iso(d){return d.toISOString().slice(0,10)}
function addDays(v,n){const d=new Date(String(v)+'T12:00:00');d.setDate(d.getDate()+n);return iso(d)}
function pretty(v){return new Intl.DateTimeFormat(ar()?'ar-EG-u-ca-gregory':'en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(v+'T12:00:00'))}
function val(id){const e=document.getElementById(id);return e&&e.value!==''?Number(e.value):null}
function textVal(id,max=100){return (document.getElementById(id)?.value||'').trim().slice(0,max)}
function rowKey(day,session){return `${day}-${session}`}
function plannedDate(state,day){return addDays(state.start||iso(new Date()),day)}
function actualDate(row,index,fallback){return row?.[`date${index}`]||fallback}
function actualTime(row,index){return row?.[`time${index}`]||''}
function readingAvg(a,b){const xs=[a,b].filter(Number.isFinite);return xs.length?xs.reduce((x,y)=>x+y,0)/xs.length:null}
function collect(){
  const state=load();
  state.start=document.getElementById('bp-start')?.value||state.start||iso(new Date());
  state.rows={};
  for(let d=0;d<DAYS;d++)for(const s of SESSIONS){
    const k=rowKey(d,s),fallback=plannedDate(state,d);
    state.rows[k]={
      date1:textVal(`bp-${k}-date1`,10)||fallback,time1:textVal(`bp-${k}-time1`,5),s1:val(`bp-${k}-s1`),d1:val(`bp-${k}-d1`),p1:val(`bp-${k}-p1`),
      date2:textVal(`bp-${k}-date2`,10)||fallback,time2:textVal(`bp-${k}-time2`,5),s2:val(`bp-${k}-s2`),d2:val(`bp-${k}-d2`),p2:val(`bp-${k}-p2`),
      note:textVal(`bp-${k}-note`,100)
    };
  }
  save(state);return state;
}
function numbers(state,fromDay=0){const out=[];for(let d=fromDay;d<DAYS;d++)for(const s of SESSIONS){const r=state.rows?.[rowKey(d,s)]||{};for(const pair of [[r.s1,r.d1],[r.s2,r.d2]])if(Number.isFinite(pair[0])&&Number.isFinite(pair[1]))out.push(pair)}return out}
function avgSummary(state,fromDay=0){const xs=numbers(state,fromDay);if(!xs.length)return null;return {sys:Math.round(xs.reduce((a,b)=>a+b[0],0)/xs.length),dia:Math.round(xs.reduce((a,b)=>a+b[1],0)/xs.length),count:xs.length}}
function points(state){
  const out=[];
  for(let d=0;d<DAYS;d++)for(const s of SESSIONS){
    const r=state.rows?.[rowKey(d,s)]||{},fallback=plannedDate(state,d);
    for(const i of [1,2]){
      const sys=r[`s${i}`],dia=r[`d${i}`];
      if(!Number.isFinite(sys)||!Number.isFinite(dia))continue;
      const date=actualDate(r,i,fallback),time=actualTime(r,i),stamp=`${date}T${time||((s==='am'?'08:':'20:')+(i===1?'00':'01'))}`;
      out.push({date,time,stamp,sys,dia,label:time||`${d+1}${s==='am'?'A':'P'}-${i}`});
    }
  }
  return out.sort((a,b)=>a.stamp.localeCompare(b.stamp));
}
function chart(state){const pts=points(state);if(!pts.length)return `<div class="bp-empty">${t('Your chart will appear after you enter readings.','سيظهر الرسم بعد إدخال القراءات.')}</div>`;const w=720,h=260,pad=38,min=40,max=Math.max(200,...pts.flatMap(p=>[p.sys,p.dia]).map(Math.ceil)),x=i=>pad+(pts.length===1?0:(w-pad*2)*i/(pts.length-1)),y=v=>h-pad-(v-min)*(h-pad*2)/(max-min);const sys=pts.map((p,i)=>`${x(i)},${y(p.sys)}`).join(' '),dia=pts.map((p,i)=>`${x(i)},${y(p.dia)}`).join(' ');return `<svg class="bp-chart-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="${t('Blood pressure trend chart','رسم اتجاه ضغط الدم')}"><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${h-pad}"/><polyline class="bp-line sys" points="${sys}"/><polyline class="bp-line dia" points="${dia}"/>${pts.map((p,i)=>`<circle class="bp-dot sys" cx="${x(i)}" cy="${y(p.sys)}" r="4"><title>${esc(p.date)} ${esc(p.time)} — ${p.sys}/${p.dia}</title></circle><circle class="bp-dot dia" cx="${x(i)}" cy="${y(p.dia)}" r="4"><title>${esc(p.date)} ${esc(p.time)} — ${p.sys}/${p.dia}</title></circle>${(i===0||i===pts.length-1||i%3===0)?`<text x="${x(i)}" y="${h-10}" text-anchor="middle">${esc(p.label)}</text>`:''}`).join('')}</svg><div class="bp-legend"><span><i class="sys"></i>${t('Top number','الرقم العلوي')}</span><span><i class="dia"></i>${t('Bottom number','الرقم السفلي')}</span></div>`}
function emergencyNotice(){return `<aside class="bp-urgent"><strong>${t('Get urgent help for very high readings with symptoms','اطلب مساعدة عاجلة عند وجود قراءة مرتفعة جدًا مع أعراض')}</strong><p>${t('If a reading is above 180/120, wait at least 1 minute and check again. If it stays that high and you have chest pain, trouble breathing, weakness, numbness, vision change, or difficulty speaking, call your local emergency service.','إذا كانت القراءة أعلى من 180/120، انتظر دقيقة واحدة ثم أعد القياس. إذا بقيت مرتفعة وظهر ألم في الصدر أو صعوبة في التنفس أو ضعف أو خدر أو تغير في النظر أو صعوبة في الكلام، اتصل بخدمة الطوارئ المحلية.')}</p></aside>`}
function technique(){return `<details class="bp-technique" open><summary>${t('How to take a good reading','الطريقة الصحيحة للقياس')}</summary><div class="bp-technique-grid"><div><b>1</b><p>${t('For 30 minutes beforehand, avoid smoking, caffeine, and exercise. Empty your bladder.','تجنب التدخين والكافيين والرياضة لمدة 30 دقيقة قبل القياس، وأفرغ المثانة.')}</p></div><div><b>2</b><p>${t('Sit quietly for 5 minutes with your back supported, feet flat, and legs uncrossed.','اجلس بهدوء 5 دقائق مع إسناد الظهر، والقدمين على الأرض، وعدم تقاطع الساقين.')}</p></div><div><b>3</b><p>${t('Put the cuff on bare upper-arm skin. Support the arm at heart level.','ضع الرباط على جلد الذراع العلوي مباشرة، واسند الذراع بمستوى القلب.')}</p></div><div><b>4</b><p>${t('Do not talk or use your phone. Take 2 readings, 1 minute apart.','لا تتحدث ولا تستخدم الهاتف. خذ قراءتين بينهما دقيقة واحدة.')}</p></div></div></details>`}
function input(id,value,min,max,label){return `<label><span>${label}</span><input id="${id}" type="number" inputmode="numeric" min="${min}" max="${max}" value="${Number.isFinite(value)?value:''}"></label>`}
function timestampFields(k,index,row,fallback){return `<div class="bp-reading-time"><label><span>${t('Actual date','التاريخ الفعلي')}</span><input id="bp-${k}-date${index}" type="date" value="${esc(actualDate(row,index,fallback))}"></label><label><span>${t('Time','الوقت')}</span><input id="bp-${k}-time${index}" type="time" step="60" value="${esc(actualTime(row,index))}"></label></div>`}
function sessionCard(state,day,s,date){const k=rowKey(day,s),r=state.rows?.[k]||{},name=s==='am'?t('Morning','صباحًا'):t('Evening','مساءً');return `<article class="bp-session"><header><strong>${name}</strong><span>${pretty(date)}</span></header><div class="bp-reading-set"><div><small>${t('Reading 1','القراءة 1')}</small>${timestampFields(k,1,r,date)}<div class="bp-reading-values">${input(`bp-${k}-s1`,r.s1,50,260,t('Top','العلوي'))}${input(`bp-${k}-d1`,r.d1,30,160,t('Bottom','السفلي'))}${input(`bp-${k}-p1`,r.p1,30,220,t('Pulse','النبض'))}</div></div><div><small>${t('Reading 2 — after 1 minute','القراءة 2 — بعد دقيقة')}</small>${timestampFields(k,2,r,date)}<div class="bp-reading-values">${input(`bp-${k}-s2`,r.s2,50,260,t('Top','العلوي'))}${input(`bp-${k}-d2`,r.d2,30,160,t('Bottom','السفلي'))}${input(`bp-${k}-p2`,r.p2,30,220,t('Pulse','النبض'))}</div></div></div><label class="bp-note"><span>${t('Note (optional)','ملاحظة اختيارية')}</span><input id="bp-${k}-note" maxlength="100" value="${esc(r.note||'')}" placeholder="${t('Example: headache, missed medicine, poor sleep','مثال: صداع، نسيان دواء، نوم سيئ')}"></label></article>`}
function render(){document.body.classList.remove('shine-intro-active','heal-intro-active','dr-intro-active');if(typeof setActive==='function')setActive('dr');const state=load();if(!state.start)state.start=iso(new Date());const all=avgSummary(state,0),afterFirst=avgSummary(state,1);document.documentElement.lang=lang();document.documentElement.dir=ar()?'rtl':'ltr';app.innerHTML=`<div class="screen bp-screen ${ar()?'rtl':''}"><section class="detail dr bp-tool"><div class="bp-head"><a class="detail-back back-control dr" href="#/dr"><span class="back-control-icon">←</span><span>${t('DR','العودة')}</span></a><button class="patient-language-toggle bp-lang" data-bp-language>${ar()?'English':'العربية'}</button></div><p class="eyebrow">${t('AT-HOME BLOOD PRESSURE','قياس ضغط الدم في المنزل')}</p><h1>${t('Your 7-day blood pressure chart','جدول ضغط الدم لمدة 7 أيام')}</h1><p class="lead">${t('Take two readings in the morning and two in the evening. Enter the actual date and time for every reading.','خذ قراءتين صباحًا وقراءتين مساءً، وسجّل التاريخ والوقت الفعلي لكل قراءة.')}</p>${emergencyNotice()}${technique()}<section class="bp-controls"><label>${t('Start date','تاريخ البداية')}<input id="bp-start" type="date" value="${state.start}"></label><button class="btn dr" data-bp-save>${t('Save readings','حفظ القراءات')}</button><button class="btn ghost" data-bp-print>${t('Print chart','طباعة الجدول')}</button><button class="btn ghost" data-bp-csv>${t('Download CSV','تنزيل ملف CSV')}</button><button class="btn ghost danger" data-bp-clear>${t('Clear chart','مسح الجدول')}</button></section><section class="bp-summary"><article><small>${t('All readings','كل القراءات')}</small><strong>${all?`${all.sys}/${all.dia}`:'—'}</strong><span>${all?t(`${all.count} readings`,`عدد القراءات: ${all.count}`):t('No readings yet','لا توجد قراءات')}</span></article><article><small>${t('Days 2–7 average','متوسط الأيام 2–7')}</small><strong>${afterFirst?`${afterFirst.sys}/${afterFirst.dia}`:'—'}</strong><span>${t('For clinic review','للمراجعة في العيادة')}</span></article></section><section class="bp-chart"><h2>${t('Trend','الاتجاه')}</h2>${chart(state)}</section><div class="bp-days">${Array.from({length:DAYS},(_,day)=>{const date=addDays(state.start,day);return `<section class="bp-day"><h2>${t(`Day ${day+1}`,`اليوم ${day+1}`)} <span>${pretty(date)}</span></h2><div class="bp-session-grid">${sessionCard(state,day,'am',date)}${sessionCard(state,day,'pm',date)}</div></section>`}).join('')}</div><aside class="bp-footnote">${t('This chart helps your clinician review a pattern. Do not stop blood pressure medicine because of a home reading unless your clinician tells you to.','يساعد هذا الجدول طبيبك على مراجعة نمط القراءات. لا توقف دواء الضغط بسبب قراءة منزلية إلا إذا طلب منك الطبيب ذلك.')}</aside></section></div>`}
function addLauncher(){if(location.hash!=='#/dr'||document.querySelector('[data-bp-launch]'))return;const root=document.querySelector('.screen');if(!root)return;const card=document.createElement('section');card.className='guided-launch bp-launch';card.dataset.bpLaunch='1';card.innerHTML=`<div><p class="eyebrow">${t('HOME TRACKING','متابعة منزلية')}</p><h2>${t('7-day blood pressure chart','جدول ضغط الدم لمدة 7 أيام')}</h2><p>${t('Record morning and evening readings and learn the correct way to measure.','سجل قراءات الصباح والمساء وتعرّف على الطريقة الصحيحة للقياس.')}</p></div><a class="btn dr button-link" href="#/dr/blood-pressure">${t('Open chart','فتح الجدول')}</a>`;root.appendChild(card)}
function csv(){const s=collect(),rows=[['Actual date','Actual time','Planned slot','Reading','Systolic','Diastolic','Pulse','Note']];for(let d=0;d<DAYS;d++)for(const sess of SESSIONS){const r=s.rows[rowKey(d,sess)]||{},fallback=plannedDate(s,d);rows.push([actualDate(r,1,fallback),actualTime(r,1),sess==='am'?'Morning':'Evening','1',r.s1??'',r.d1??'',r.p1??'',r.note||''],[actualDate(r,2,fallback),actualTime(r,2),sess==='am'?'Morning':'Evening','2',r.s2??'',r.d2??'',r.p2??'',r.note||''])}const text=rows.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\r\n'),blob=new Blob([text],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='home-blood-pressure.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
const previousRoute=window.route;window.route=function(){if(location.hash==='#/dr/blood-pressure'){render();if(typeof focusPageHeading==='function')focusPageHeading();return}const result=previousRoute.apply(this,arguments);requestAnimationFrame(addLauncher);return result};
document.addEventListener('click',e=>{if(e.target.closest('[data-bp-save]')){collect();render();return}if(e.target.closest('[data-bp-print]')){collect();window.print();return}if(e.target.closest('[data-bp-csv]')){csv();return}if(e.target.closest('[data-bp-clear]')){if(confirm(t('Clear all blood pressure readings?','مسح جميع قراءات ضغط الدم؟'))){localStorage.removeItem(KEY);render()}return}if(e.target.closest('[data-bp-language]')){localStorage.setItem(LANG_KEY,ar()?'en':'ar');render();return}});
document.addEventListener('change',e=>{if(e.target.id==='bp-start'){const s=load();s.start=e.target.value;save(s);render()}});
if(location.hash==='#/dr/blood-pressure')render();else requestAnimationFrame(addLauncher);
})();