// IF YOU HAVE NOT ALREADY READ PATIENT_CARE_RULES.md, STOP AND READ IT BEFORE EDITING THIS FILE.
(function(){
'use strict';
const IRON_PROGRESS_PREFIX='pc_iron_progress_';
const ORAL_PRESETS={
  sulfate:{label:'Ferrous sulfate',productMg:325,elementalMg:65},
  fumarate:{label:'Ferrous fumarate',productMg:200,elementalMg:65},
  gluconate:{label:'Ferrous gluconate',productMg:300,elementalMg:35},
  liposomal:{label:'Liposomal iron',productMg:'',elementalMg:''},
  custom:{label:'Custom oral iron product',productMg:'',elementalMg:''}
};
const IV_PRODUCTS=['Iron sucrose','Ferric carboxymaltose','Ferric derisomaltose','Ferumoxytol','Ferric gluconate','Low-molecular-weight iron dextran','Custom IV iron product'];
function iEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function iDate(v){return new Date(String(v)+'T12:00:00')}
function iIso(d){return d.toISOString().slice(0,10)}
function iAddDays(v,n){const d=typeof v==='string'?iDate(v):new Date(v);d.setDate(d.getDate()+n);return d}
function iPretty(v){return iDate(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function iEncode(v){return btoa(unescape(encodeURIComponent(JSON.stringify(v)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function iDecode(v){try{const s=String(v).replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(decodeURIComponent(escape(atob(s+'==='.slice((s.length+3)%4))))}catch(e){return null}}
function iHash(code){let h=2166136261;for(let i=0;i<code.length;i++){h^=code.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function iProgressKey(code){return IRON_PROGRESS_PREFIX+iHash(code)}
function iLoad(code){try{return new Set(JSON.parse(localStorage.getItem(iProgressKey(code)))||[])}catch(e){return new Set()}}
function iSave(code,set){localStorage.setItem(iProgressKey(code),JSON.stringify([...set]))}
function patientUrl(kind,data){return location.origin+location.pathname+location.search+'#/patient/iron-'+kind+'/'+iEncode(data)}
function qrInto(id,url){const el=document.getElementById(id);if(!el)return;try{const qr=qrcode(0,'M');qr.addData(url);qr.make();el.innerHTML=qr.createSvgTag({cellSize:5,margin:4,scalable:true})}catch(e){el.textContent='Use the patient link.'}}
function physicianHeader(title,text){return `<a class="detail-back back-control dr" href="#/physician"><span class="back-control-icon">←</span><span>Physician Mode</span></a><header><p class="eyebrow">PHYSICIAN MODE / IRON</p><h1>${iEsc(title)}</h1><p>${iEsc(text)}</p></header>`}
window.renderPhysicianMode=function(){
  document.body.classList.add('physician-mode-active');document.body.classList.remove('vitd-patient-active','iron-patient-active');setActive('summary');
  app.innerHTML=`<div class="screen physician-screen"><section class="physician-hero"><div class="physician-mark" aria-hidden="true">✚</div><div><p class="eyebrow">CLINICIAN TOOLS</p><h1>Physician Mode</h1><p>Clinician-confirmed calculators and patient schedules without patient-identifying information in the link.</p></div></section><section class="physician-tool-grid"><a class="physician-tool-card" href="#/physician/vitamin-d"><span aria-hidden="true">☀</span><div><small>VITAMIN D</small><h2>Vitamin D schedule</h2><p>Adult reference and local clinic pathways with QR handoff.</p></div><b>Open →</b></a><a class="physician-tool-card iron-card" href="#/physician/iron-oral"><span aria-hidden="true">Fe</span><div><small>ORAL IRON</small><h2>Oral iron calculator</h2><p>Calculate elemental iron and create daily or every-two-days schedules.</p></div><b>Open →</b></a><a class="physician-tool-card iron-card iv" href="#/physician/iron-iv"><span aria-hidden="true">IV</span><div><small>IV IRON</small><h2>IV iron calculator</h2><p>Plan formulation-specific infusion doses and appointment dates.</p></div><b>Open →</b></a></section><aside class="physician-warning"><strong>Clinician use only.</strong> Confirm the exact product label, institutional protocol, contraindications, monitoring, and administration requirements before patient handoff.</aside><a class="btn ghost button-link" href="#/plan">Return to Your Plan</a></div>`;
};
window.renderOralIronTool=function(){
  document.body.classList.add('physician-mode-active');document.body.classList.remove('iron-patient-active');setActive('summary');
  const today=new Date().toISOString().slice(0,10),repeat=iIso(iAddDays(today,84));
  app.innerHTML=`<div class="screen physician-screen"><section class="vitd-builder iron-builder">${physicianHeader('Oral iron calculator & scheduler','Calculate elemental iron from the confirmed product label and generate a dated patient schedule.')}<form id="oral-iron-form"><div class="vitd-form-grid"><label>Formulation<select id="oral-formulation">${Object.entries(ORAL_PRESETS).map(([k,p])=>`<option value="${k}">${p.label}</option>`).join('')}</select></label><label>Product strength per unit (mg)<input id="oral-product-mg" type="number" min="0.1" step="0.1" value="325" required></label><label>Elemental iron per unit (mg)<input id="oral-elemental-mg" type="number" min="0.1" step="0.1" value="65" required></label><label>Units per dose<input id="oral-units" type="number" min="0.25" max="10" step="0.25" value="1" required></label><label>Frequency<select id="oral-frequency"><option value="2" selected>Every 2 days</option><option value="1">Once daily</option><option value="3">Every 3 days</option></select></label><label>Course duration (weeks)<input id="oral-weeks" type="number" min="1" max="52" value="12" required></label><label>First dose date<input id="oral-start" type="date" value="${today}" required></label><label>Repeat CBC / iron studies date<input id="oral-repeat" type="date" value="${repeat}" required></label><label class="vitd-clinic-field">Product or clinic label (optional)<input id="oral-label" maxlength="80" placeholder="Brand, formulation, or clinic"></label></div><div id="oral-preview" class="vitd-protocol-preview"></div><fieldset class="vitd-safety"><legend>Required clinician confirmations</legend><label><input type="checkbox" required><span>I confirmed the exact elemental iron amount from the dispensed product label.</span></label><label><input type="checkbox" required><span>I reviewed the indication, interactions, contraindications, tolerability, follow-up laboratory plan, and local instructions.</span></label><label><input type="checkbox" required><span>I independently selected this dose and frequency. The app is calculating and scheduling only.</span></label></fieldset><button class="btn dr vitd-generate" type="submit">Confirm and generate oral iron schedule</button></form><section id="oral-export" class="vitd-export" hidden></section></section></div>`;
  updateOralPreview();
};
function oralData(){const form=document.getElementById('oral-formulation'),preset=ORAL_PRESETS[form?.value]||ORAL_PRESETS.custom,product=Number(document.getElementById('oral-product-mg')?.value),elemental=Number(document.getElementById('oral-elemental-mg')?.value),units=Number(document.getElementById('oral-units')?.value),gap=Number(document.getElementById('oral-frequency')?.value),weeks=Number(document.getElementById('oral-weeks')?.value),start=document.getElementById('oral-start')?.value,repeat=document.getElementById('oral-repeat')?.value,label=document.getElementById('oral-label')?.value.trim().slice(0,80);if(!product||!elemental||!units||!gap||!weeks||!start||!repeat)return null;const count=Math.floor((weeks*7-1)/gap)+1,dates=Array.from({length:count},(_,i)=>iIso(iAddDays(start,i*gap)));return {v:1,kind:'oral',f:preset.label,pm:product,em:elemental,u:units,ed:Number((elemental*units).toFixed(2)),g:gap,w:weeks,s:start,r:repeat,d:dates,c:label}}
function updateOralPreview(){const out=document.getElementById('oral-preview');if(!out)return;const d=oralData();if(!d){out.innerHTML='<strong>Complete the product and schedule fields.</strong>';return}out.innerHTML=`<strong>${d.ed} mg elemental iron per dose</strong><span>${d.u} unit${d.u===1?'':'s'} of ${iEsc(d.f)}, every ${d.g===1?'day':d.g+' days'}, for ${d.d.length} planned doses. Repeat labs: ${iPretty(d.r)}.</span>`}
function renderOralExport(d){const target=document.getElementById('oral-export'),url=patientUrl('oral',d);target.hidden=false;target.dataset.schedule=iEncode(d);target.innerHTML=`<div class="vitd-export-head"><div><p class="eyebrow">PATIENT HANDOFF</p><h2>Oral iron journey is ready</h2><p>Review the product, elemental dose, frequency, and every date before handoff.</p></div><div id="oral-qr" class="vitd-qr"></div></div><div class="vitd-export-summary"><article><small>Formulation</small><strong>${iEsc(d.f)}</strong><span>${d.pm} mg product strength per unit</span></article><article><small>Elemental dose</small><strong>${d.ed} mg</strong><span>${d.u} unit${d.u===1?'':'s'} every ${d.g===1?'day':d.g+' days'}</span></article><article><small>Schedule</small><strong>${d.d.length} doses</strong><span>Repeat labs ${iPretty(d.r)}</span></article></div><label class="vitd-link-label">Patient link<input id="oral-link" readonly value="${iEsc(url)}"></label><div class="vitd-export-actions"><button class="btn dr" data-open-oral-patient>Open patient page</button><button class="btn ghost" data-copy-oral-link>Copy link</button></div>`;qrInto('oral-qr',url);target.scrollIntoView({behavior:'smooth',block:'start'})}
window.renderIvIronTool=function(){
  document.body.classList.add('physician-mode-active');document.body.classList.remove('iron-patient-active');setActive('summary');
  const today=new Date().toISOString().slice(0,10),repeat=iIso(iAddDays(today,56));
  app.innerHTML=`<div class="screen physician-screen"><section class="vitd-builder iron-builder">${physicianHeader('IV iron calculator & scheduler','Enter the prescribed total iron and the confirmed product-specific administration limits. The app will not choose an IV regimen autonomously.')}<form id="iv-iron-form"><div class="vitd-form-grid"><label>IV formulation<select id="iv-product">${IV_PRODUCTS.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Prescribed total iron (mg)<input id="iv-total" type="number" min="1" max="10000" step="1" value="1000" required></label><label>Planned dose per infusion (mg)<input id="iv-dose" type="number" min="1" max="5000" step="1" value="200" required></label><label>Confirmed maximum per administration (mg)<input id="iv-max" type="number" min="1" max="5000" step="1" value="200" required></label><label>Days between infusions<input id="iv-gap" type="number" min="1" max="90" value="2" required></label><label>First infusion date<input id="iv-start" type="date" value="${today}" required></label><label>Repeat CBC / ferritin / TSAT date<input id="iv-repeat" type="date" value="${repeat}" required></label><label class="vitd-clinic-field">Clinic or infusion service (optional)<input id="iv-clinic" maxlength="80"></label></div><div id="iv-preview" class="vitd-protocol-preview"></div><fieldset class="vitd-safety"><legend>Required clinician confirmations</legend><label><input type="checkbox" required><span>I confirmed the exact IV product, prescribing information, maximum administration dose, dilution, infusion rate, and observation requirements.</span></label><label><input type="checkbox" required><span>I reviewed hypersensitivity risk, prior reactions, pregnancy status, infection considerations, laboratory data, and institutional emergency procedures.</span></label><label><input type="checkbox" required><span>The prescribed total iron and infusion schedule were independently selected by a clinician.</span></label></fieldset><button class="btn dr vitd-generate" type="submit">Confirm and generate IV iron schedule</button></form><section id="iv-export" class="vitd-export" hidden></section></section></div>`;
  updateIvPreview();
};
function ivData(){const product=document.getElementById('iv-product')?.value,total=Number(document.getElementById('iv-total')?.value),dose=Number(document.getElementById('iv-dose')?.value),max=Number(document.getElementById('iv-max')?.value),gap=Number(document.getElementById('iv-gap')?.value),start=document.getElementById('iv-start')?.value,repeat=document.getElementById('iv-repeat')?.value,clinic=document.getElementById('iv-clinic')?.value.trim().slice(0,80);if(!product||!total||!dose||!max||!gap||!start||!repeat)return null;const n=Math.ceil(total/dose),infusions=Array.from({length:n},(_,i)=>({date:iIso(iAddDays(start,i*gap)),mg:i===n-1?total-dose*(n-1):dose}));return {v:1,kind:'iv',p:product,t:total,dp:dose,mx:max,g:gap,s:start,r:repeat,i:infusions,c:clinic,over:dose>max||infusions.some(x=>x.mg>max)}}
function updateIvPreview(){const out=document.getElementById('iv-preview');if(!out)return;const d=ivData();if(!d){out.innerHTML='<strong>Complete the IV product and schedule fields.</strong>';return}out.classList.toggle('out-of-range',d.over);out.innerHTML=d.over?`<strong>Planned dose exceeds the confirmed maximum.</strong><span>Reduce the dose per infusion or correct the maximum before generating.</span>`:`<strong>${d.i.length} planned infusion${d.i.length===1?'':'s'}</strong><span>${d.t} mg total ${iEsc(d.p)}; ${d.dp} mg per infusion${d.i.at(-1).mg!==d.dp?', final dose '+d.i.at(-1).mg+' mg':''}; every ${d.g} day${d.g===1?'':'s'}.</span>`}
function renderIvExport(d){const target=document.getElementById('iv-export'),url=patientUrl('iv',d);target.hidden=false;target.dataset.schedule=iEncode(d);target.innerHTML=`<div class="vitd-export-head"><div><p class="eyebrow">PATIENT HANDOFF</p><h2>IV iron schedule is ready</h2><p>Review every appointment, product, and dose before handoff.</p></div><div id="iv-qr" class="vitd-qr"></div></div><div class="vitd-export-summary"><article><small>Product</small><strong>${iEsc(d.p)}</strong></article><article><small>Total prescribed iron</small><strong>${d.t} mg</strong><span>${d.i.length} infusion${d.i.length===1?'':'s'}</span></article><article><small>Repeat labs</small><strong>${iPretty(d.r)}</strong></article></div><label class="vitd-link-label">Patient link<input id="iv-link" readonly value="${iEsc(url)}"></label><div class="vitd-export-actions"><button class="btn dr" data-open-iv-patient>Open patient page</button><button class="btn ghost" data-copy-iv-link>Copy link</button></div>`;qrInto('iv-qr',url);target.scrollIntoView({behavior:'smooth',block:'start'})}
function renderIronPatient(kind,code){const d=iDecode(code);document.body.classList.add('iron-patient-active');document.body.classList.remove('physician-mode-active','vitd-patient-active');if(!d||d.kind!==kind){app.innerHTML='<div class="screen"><section class="detail"><h1>This iron schedule link is invalid</h1><p>Ask the clinic to generate a new link.</p></section></div>';return}const done=iLoad(code),items=kind==='oral'?d.d.map((date,i)=>({id:'o'+i,date,main:`${d.ed} mg elemental iron`,sub:`${d.u} unit${d.u===1?'':'s'} · every ${d.g===1?'day':d.g+' days'}`})):d.i.map((x,i)=>({id:'i'+i,date:x.date,main:`${x.mg} mg ${d.p}`,sub:`Infusion ${i+1} of ${d.i.length}`}));const completed=items.filter(x=>done.has(x.id)).length;app.innerHTML=`<div class="vitd-patient-page iron-patient-page"><header class="vitd-journey-hero iron-hero"><div class="vitd-sun"><span>Fe</span></div><p class="eyebrow">YOUR IRON JOURNEY</p><h1>${kind==='oral'?'Oral iron schedule':'IV iron appointments'}</h1><p>${d.c?iEsc(d.c)+' prepared this schedule. ':''}Follow only the confirmed product, dose, and dates shown.</p><div class="vitd-progress"><div><span style="width:${Math.round(completed/Math.max(items.length,1)*100)}%"></span></div><strong>${completed} of ${items.length} completed</strong></div></header><main class="vitd-journey-main"><section class="vitd-phase"><div class="vitd-phase-head"><span>Fe</span><div><small>${kind==='oral'?'DOSE SCHEDULE':'INFUSION SCHEDULE'}</small><h2>${kind==='oral'?iEsc(d.f):iEsc(d.p)}</h2></div></div><div class="vitd-dose-list">${items.map(x=>`<label class="vitd-dose-card ${done.has(x.id)?'done':''}"><input type="checkbox" data-iron-dose="${x.id}" ${done.has(x.id)?'checked':''}><span class="vitd-dose-check">${done.has(x.id)?'✓':''}</span><span><small>${iEsc(x.sub)}</small><strong>${iPretty(x.date)}</strong><em>${iEsc(x.main)}</em></span></label>`).join('')}</div></section><section class="vitd-repeat"><span>🧪</span><div><small>REPEAT LABORATORY REVIEW</small><h2>${iPretty(d.r)}</h2><p>Follow the clinic’s instructions for laboratory testing and further treatment decisions.</p></div></section><section class="vitd-save-card"><h2>Save this schedule</h2><div class="vitd-save-actions"><button class="btn dr" data-share-iron>Share or save link</button><button class="btn ghost" data-copy-iron>Copy link</button></div><details><summary>Add to your Home Screen</summary><div class="vitd-home-help"><p><strong>iPhone:</strong> Safari → Share → Add to Home Screen.</p><p><strong>Android:</strong> Chrome menu → Add to Home screen.</p></div></details></section><aside class="vitd-patient-safety"><strong>Use only the confirmed schedule.</strong><p>Contact the clinic when the product, strength, dose, infusion appointment, or medical situation differs from what is shown.</p></aside></main></div>`;app.dataset.ironCode=code}
function handleRoute(){const h=location.hash;if(h==='#/physician'){renderPhysicianMode();return true}if(h==='#/physician/iron-oral'){renderOralIronTool();return true}if(h==='#/physician/iron-iv'){renderIvIronTool();return true}if(h.startsWith('#/patient/iron-oral/')){renderIronPatient('oral',h.slice('#/patient/iron-oral/'.length));return true}if(h.startsWith('#/patient/iron-iv/')){renderIronPatient('iv',h.slice('#/patient/iron-iv/'.length));return true}return false}
document.addEventListener('change',e=>{if(e.target.id==='oral-formulation'){const p=ORAL_PRESETS[e.target.value];if(p&&p.productMg){document.getElementById('oral-product-mg').value=p.productMg;document.getElementById('oral-elemental-mg').value=p.elementalMg}else{document.getElementById('oral-product-mg').value='';document.getElementById('oral-elemental-mg').value=''}updateOralPreview()}if(e.target.matches('#oral-iron-form input,#oral-iron-form select'))updateOralPreview();if(e.target.matches('#iv-iron-form input,#iv-iron-form select'))updateIvPreview();const cb=e.target.closest?.('[data-iron-dose]');if(cb){const code=app.dataset.ironCode;if(!code)return;const done=iLoad(code);cb.checked?done.add(cb.dataset.ironDose):done.delete(cb.dataset.ironDose);iSave(code,done);handleRoute()}});
document.addEventListener('input',e=>{if(e.target.matches('#oral-iron-form input,#oral-iron-form select'))updateOralPreview();if(e.target.matches('#iv-iron-form input,#iv-iron-form select'))updateIvPreview()});
document.addEventListener('submit',e=>{if(e.target.id==='oral-iron-form'){e.preventDefault();const d=oralData();if(d)renderOralExport(d)}if(e.target.id==='iv-iron-form'){e.preventDefault();const d=ivData();if(!d)return;if(d.over){alert('The planned IV dose exceeds the confirmed maximum per administration.');return}renderIvExport(d)}});
document.addEventListener('click',async e=>{const oral=document.getElementById('oral-export')?.dataset.schedule,iv=document.getElementById('iv-export')?.dataset.schedule;if(e.target.closest('[data-open-oral-patient]')&&oral){location.hash='#/patient/iron-oral/'+oral;return}if(e.target.closest('[data-open-iv-patient]')&&iv){location.hash='#/patient/iron-iv/'+iv;return}if(e.target.closest('[data-copy-oral-link]')){await navigator.clipboard?.writeText(document.getElementById('oral-link')?.value||'');showToast('Patient link copied');return}if(e.target.closest('[data-copy-iv-link]')){await navigator.clipboard?.writeText(document.getElementById('iv-link')?.value||'');showToast('Patient link copied');return}if(e.target.closest('[data-copy-iron]')){await navigator.clipboard?.writeText(location.href);showToast('Schedule link copied');return}if(e.target.closest('[data-share-iron]')){if(navigator.share)await navigator.share({title:'Iron Journey',text:'Open the clinician-confirmed iron schedule',url:location.href});else{await navigator.clipboard?.writeText(location.href);showToast('Schedule link copied')}}});
window.addEventListener('hashchange',()=>setTimeout(handleRoute,0));
handleRoute();
})();